### PR TITLE
creates the browser builder based on what is configured rather than on…

### PR DESCRIPTION
**Pull request by adamclerk**
… the angular-devkit/build-angular:browser

I'm using a custom builder for webpack with my build. I need to the same build with the cordova commands. 

I'm not sure if this the correct approach: please provide direction if it is not.

### CODE REVIEW

**Comment by dwieeb** [comment]
I think this is actually where we'd want to use `architect.getBuilder()`, which instantiates a builder from the workspace configuration. I had a TODO in there because I figured people may need to use custom builders eventually.

**Comment by dwieeb** [comment]
@adamclerk Give me a few days to wrap up some stuff and I'll circle back with better feedback.

I made an issue we can track this with: https://github.com/ionic-team/angular-toolkit/issues/32

**Comment by adamclerk** [comment]
Let me take another crack at it this evening.

**Comment by dwieeb** [comment]
@adamclerk FYI: I updated the dependencies to support Angular 7. I had to remove `node_modules` and reinstall before the compilation worked again.

**Comment by dwieeb** [comment]
@adamclerk Probably not good to read the `angular.json` file in, the configuration is already known to architect. 

I think I was able to accomplish this with the following run method:

```ts
  run(builderConfig: BuilderConfiguration<CordovaBuildBuilderSchema>): Observable<BuildEvent> {
    const [ project, target, configuration ] = builderConfig.options.browserTarget.split(':');
    const browserTargetSpec = { project, target, configuration, overrides: {} };

    let browserConfig = this.context.architect.getBuilderConfiguration<BrowserBuilderSchema>(browserTargetSpec);
    let browserDescription: BuilderDescription;

    return of(null).pipe(// tslint:disable-line:no-null-keyword
      concatMap(() => this.context.architect.getBuilderDescription(browserConfig)),
      tap(description => browserDescription = description),
      concatMap(() => this.context.architect.validateBuilderOptions(browserConfig, browserDescription)),
      tap(config => browserConfig = config),
      tap(() => this.prepareBrowserConfig(builderConfig.options, browserConfig.options)),
      concatMap(() => of(this.context.architect.getBuilder(browserDescription, this.context))),
      concatMap(builder => builder.run(browserConfig))
    );
  }

```

**Comment by adamclerk** [comment]
I am. But have been pulled in a different direction for the past week. I can probably take another crack at it on Friday.

**Comment by dwieeb** [comment]
@adamclerk Just another ping. The framework is now in RC, and I think this should be included before 4.0 final is released. I'm not trying to pressure you, but I consider this a bug and would like to fix it before we release.

**Comment by adamclerk** [comment]
I'm so sorry. I don't think I'll be able to take this on.

**Comment by dwieeb** [comment]
@adamclerk No worries! I'll finish it up and add you as a co-author. 👍

**Pull request closed without merging**
