### PR TITLE
build(deps): update Angular from 11.1.0 to 11.2.4

### PR DESCRIPTION
**Pull request by Juneezee**
Angular 11.2.0 was released the day PR #438 got merged.

EDIT: There are newer Angular 11.2 patch releases since this pull request was created, and I have updated the branch accordingly.

### CODE REVIEW

**Comment by mhartington** [comment]
I actually dont know if this needed, since semver should auto install the latest minor/patch release.

**Comment by Juneezee** [comment]
> I actually dont know if this needed, since semver should auto install the latest minor/patch release.

See #444

**Comment by m8xp0w3r** [comment]
> I actually dont know if this needed, since semver should auto install the latest minor/patch release.

As long as this is < 11.2 that happens on `npm install`:
image

**Comment by m8xp0w3r** [comment]
@mhartington without updating to angular x.2.x npm install always throws a bunch of warnings which makes the usage not very comfortable. It would be awesome if this angular update would be used here.

**Pull request closed without merging**
