### PR TITLE
feat: bump deps to angular 15

### PR DESCRIPTION
**Pull request by ChrisZinnecker**
currently live reload is not working, if you update a project to angular 15

```bash
> ng run app:ionic-cordova-serve --host=localhost --port=8100 --platform=ios
[ng] This version of CLI is only compatible with Angular versions ^14.0.0,
[ng] but Angular version 15.0.1 was found instead.
```

### CODE REVIEW

**Comment by QuentinFarizon** [comment]
Hello @mhartington, can we get this merged ? It blocks using Angular 15
Thanks !

**Comment by mhartington** [comment]
1) Please do not ping, it just adds noise.
2) Upgrading cordova-builders to support ng15 is more than just bumping the versions of deps. There is a dep on internal APIs that are needed, which are likely to change.

**Comment by QuentinFarizon** [comment]
Angular 15 is out since a month now. Do you have a status on supporting it ?

**Comment by QuentinFarizon** [comment]
Hello, Angular 15 is out since two months. Is Angular still supported by Ionic ?

**Pull request closed without merging**
