### PR TITLE
Updated dependencies and code to accommodate angular 11

### PR DESCRIPTION
**Pull request by J4cku**
#380

### CODE REVIEW

**Comment by mhartington** [comment]
Looks good. This is likely to be a braking change since the imports paths change, but otherwise, I'll get to this this week.

**Comment by J4cku** [comment]
Oh, yes - surely breaking change, but I did not feel comfortable versioning it

**Comment by mhartington** [comment]
@J4cku it's ok, CI takes care of the versioning, so no need to do that yourself! Thank you for the PR!

**Pull request closed without merging**
